{
	"_Type": "Action.Type.RestService.SendRequest",
	"OnFailure": {
		"Name": "/mdk06/Actions/GenericToastMessage.action",
		"Properties": {
			"Message": "Error"
		}
	},
	"Target": {
		"Service": "/mdk06/Services/AI_API.service",
		"Path": "/completion",
		"RequestProperties": {
			"Method": "POST",
			"Headers": {
				"AI-Resource-Group": "default"
			},
			"Body": "{#Application/#ClientData/body}"
		}
	}
}